var json_eprosec_fig_6 = {
"type": "FeatureCollection",
"name": "eprosec_fig_6",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "RA210", "descriptio": "<html xmlns:fo=\"http:\/\/www.w3.org\/1999\/XSL\/Format\" xmlns:msxsl=\"urn:schemas-microsoft-com:xslt\">\n\n<head>\n\n<META http-equiv=\"Content-Type\" content=\"text\/html\">\n\n<meta http-equiv=\"content-type\" content=\"text\/html; charset=UTF-8\">\n\n<\/head>\n\n<body style=\"mar", "timestamp": null, "begin": null, "end": null, "altitudeMo": "clampToGround", "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "snippet": null, "NE": "RA210", "CIRCUITO": "FIG04120", "TIPO_EQUIP": "UTR TIPO POSTE", "ENLACE": null, "LAT": "25.705769", "LON": "-100.158194", "OID": "104", "INICIO": "17:58", "TERMINO": null, "circuito_1": "VSL04260", "EQUIPO": "RA210", "EVENTOS": "11", "MW": "0", "CLIENTE": null, "ZONA": "11", "FECHA": "31.may", "COD_FALLA": "RR" }, "geometry": { "type": "Point", "coordinates": [ -100.1581944, 25.7057694 ] } },
{ "type": "Feature", "properties": { "Name": "RA805", "descriptio": "<html xmlns:fo=\"http:\/\/www.w3.org\/1999\/XSL\/Format\" xmlns:msxsl=\"urn:schemas-microsoft-com:xslt\">\n\n<head>\n\n<META http-equiv=\"Content-Type\" content=\"text\/html\">\n\n<meta http-equiv=\"content-type\" content=\"text\/html; charset=UTF-8\">\n\n<\/head>\n\n<body style=\"mar", "timestamp": null, "begin": null, "end": null, "altitudeMo": "clampToGround", "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null, "snippet": null, "NE": "RA805", "CIRCUITO": "FIG04120", "TIPO_EQUIP": "UTR TIPO POSTE", "ENLACE": null, "LAT": "25.710978", "LON": "-100.157286", "OID": "129", "INICIO": "18:46", "TERMINO": null, "circuito_1": "JZO04255", "EQUIPO": "RA805", "EVENTOS": "1", "MW": "0", "CLIENTE": null, "ZONA": "11", "FECHA": "27.ago", "COD_FALLA": "RR" }, "geometry": { "type": "Point", "coordinates": [ -100.1572861, 25.7109778 ] } }
]
}
